name: Build and push Docker image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master

      - name: Build image
        run: |
          cd src/Web/
          docker build . -t khunpheakdeyson/eshopwebmvc:latest
          docker build . -t khunpheakdeyson/eshopwebmvc:v2

      - name: Run Trivy scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: khunpheakdeyson/eshopwebmvc:latest
          severity: CRITICAL
          format: table
          output: console
          fail-on-severity: CRITICAL

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push image to Docker Hub
        run: |
          echo "Push image to Docker Hub..."
          docker push khunpheakdeyson/eshopwebmvc:latest
          docker push khunpheakdeyson/eshopwebmvc:v2